---
title: "tree"
output: html_document
---

running

```{r}
purl("Rscripts/tree.Rmd")
system("nohup R --no-save < tree.R", wait = FALSE)
```

```{r}
install.packages("plyr")
install.packages("rpart")
install.packages("grid")
install.packages("RWeka")
install.packages("rattle")
install.packages("RColorBrewer")
install.packages("pander")
install.packages("data.table")
install.packages("knitr")
install.packages("printr")
install.packages("raster")
install.packages("RNCEP")
install.packages("udunits2")
install.packages("devtools")
install.packages("ggplot2")

```


Loading libraries:
```{r}
library(plyr)#try_default
library(rpart)
library(grid)
library(partykit)
library(RWeka)
library(RColorBrewer)
library(pander)
library(data.table)
library(knitr)
library(devtools)
library(RNCEP)
library(ggplot2)
opts_chunk$set(echo = FALSE, message = FALSE, warnings = FALSE,  cache = FALSE)
```


## Data Prep

```{r}
download.file("https://raw.githubusercontent.com/sidewallme/2015-Rose-Hulman-Competition/master/clean_yields.csv", method = 'curl', destfile = 'clean_yields.csv')
yields <- fread("clean_yields.csv")

```

```{r data-load}
miscanthus <- yields
m <- miscanthus[!(is.na(planting_density) | is.na(yield)),
                `:=`(sacchariflorus = grepl('sacchariflorus', species),
                     sinensis = grepl('sinensis', species),
                     sinensis.Hybrid = grepl('Hybrid', species),
                     giganteus = grepl('giganteus', species))]

m$yields.id <- NULL # remove yields.id
```

### Climate Data

#### WorldClim

```{r worldclim, eval=FALSE}
library(raster)

x <- getData('worldclim', var='tmin', res=0.5, lon=5, lat=45)

ans <- m[1, list(tmin = getData('worldclim', var = 'tmin', res = 0.5, lon = lon, lat = lat))]
```


#### RNCEP

```{r rncep}
unique_xyt <- unique(yields[,list(lat, lon, year) ])

get_met <- function(year, lat, lon, var){
  ans <- NULL
  ans <- try_default(quiet = TRUE, default = NA, expr = 
                       NCEP.gather(variable = var, level='gaussian', months.minmax=c(5,9), years.minmax = c(year,year), lat.southnorth = c(lat,lat), lon.westeast=c(lon,lon), reanalysis2 = TRUE, return.units = FALSE, status.bar=FALSE)
                     )
  print(ans)

  if(any(!is.na(ans))){
    lats <- as.numeric(dimnames(ans)[[1]])
    lons <- as.numeric(dimnames(ans)[[2]])
    lons[lons>180] <- lons[lons>180] - 360
    dlat <- abs(lat - lats)
    dlon <- abs(lon - lons)
    #weights
    wlat <- dlat/sum(dlat, na.rm = TRUE)
    wlon <- dlon/sum(dlon, na.rm = TRUE)

    weights <- as.matrix(wlat) %*% t(as.matrix(wlon))


    ans2 <- rowMeans(ans, dims = 2, na.rm = TRUE)
    ans2.1 <- ans2[!is.nan(ans2)]

    ans3 <- sum(ans2.1 * weights)
    ans <- ans3
    }


  return(ans)
  }


s2year <- udunits2::ud.convert(1, '1/s', '1/year')
## MAT = Mean Annual Temperature
ncep_data_list <- list()
for(i in 1:nrow(unique_xyt)){
  ncep_data_list[[i]] <- unique_xyt[i, list(lat, lon, year, MAT = mean(get_met(year, lat, lon, 'air.2m')),
                                      MAP = sum(get_met(year, lat, lon, 'prate.sfc')),
                                      PET = mean(get_met(year, lat, lon, 'pevpr.sfc')),
                                      SOLAR = sum(get_met(year, lat, lon, 'dswrf.sfc'))
                                      )]


  ncep_data <- rbindlist(ncep_data_list)
  save(ncep_data, file = "~/ncep_data.RData") 
  }


ggplot() + geom_point(data = ncep_data, aes(lon, lat, color = MAP/PET))

```


#### Daymet

_note:_ daymet only covers US, Canada, Mexico

```{r daymet, eval=FALSE}
if(require(DaymetR)){
  install_bitbucket("khufkens/daymetr", subdir = 'DaymetR')
} 
library(DaymetR)

dm <- list()
new_xyt <- unique_xyt[unique_xyt$lon < -30,]
for(i in 1:nrow(new_xyt)){
  rm(Daymet)
  try(
    new_xyt[i, download.daymet(lat = lat, lon = lon,internal = FALSE,  start_yr = year, end_yr = year)]
    )
  
  if(exists("Daymet")){
    d <- data.table(Daymet$data)

    dm[[i]] <- d[yday > 90 & yday < 270,
                 list(lat = Daymet$lattitude,
                      lon = Daymet$longitude,
                      elev = Daymet$altitude,
                      year = unique(year),
                      temp = mean(c(tmax..deg.c., 
                                    tmin..deg.c.)),
                      precip = sum(prcp..mm.day.),
                      vpd = mean(vp..Pa.))]
    } else {
      dm[[i]] <- NA
    }
  save(dm, file = "data/daymet.RData")
}

```
## Analyses


### Regression Tree

```{r reg-tree}
rtree <- rpart(yield ~ sacchariflorus + sinensis + sinensis.Hybrid + giganteus +
                 lat + lon + fertilizer_n + stand_age + irrigated + planting_density, 
               data = m)

plot(as.party(rtree),tp_args=list(id=FALSE))

pander(rtree$cptable)

opt <- which.min(rtree$cptable[,"xerror"])
cp <- rtree$cptable[opt,"CP"]

rtree_prune <- prune(rtree,cp=cp)
plot(as.party(rtree_prune),tp_args=list(id=FALSE))

fit <- rpart(yield~., method="anova", data=dataigb2_rtree)

summary(rtree)
```

TODO what do you see? what does it mean?

## Using M5P algorithm

```{r M5P}

m2 <- m[,list(yield, sacchariflorus = as.numeric(sacchariflorus), 
              sinensis = as.integer(sinensis), 
              sinensis.Hybrid = as.integer(sinensis.Hybrid), 
              giganteus = as.integer(giganteus),
              irrigated = as.integer(irrigated),
              lat, lon, fertilizer_n,  planting_density)]
m2[] <- lapply(m2, as.numeric)

m5pTree <- M5P(yield ~ sacchariflorus + sinensis + sinensis.Hybrid + giganteus +
                 lat + lon + fertilizer_n + irrigated + planting_density, 
         data = m2)


summary(m5pTree)
plot(m5pTree)

```
TODO what do you see? what does it mean?